// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EADCA3Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void navigationTest() {
    driver.Navigate().GoToUrl("https://shemulhossain.github.io/EAD_CA3/");
    driver.Manage().Window.Size = new System.Drawing.Size(968, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.LinkText("Search Books")).Click();
    driver.Close();
  }
  [Test]
  public void detailsTest() {
    driver.Navigate().GoToUrl("https://shemulhossain.github.io/EAD_CA3/");
    driver.Manage().Window.Size = new System.Drawing.Size(968, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-input"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".search-input")).Click();
    driver.FindElement(By.CssSelector(".search-input")).SendKeys("Harry Potter");
    driver.FindElement(By.CssSelector(".search-button")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".book-item:nth-child(1)")).Click();
    driver.FindElement(By.LinkText("Harry Potter and the Philosopher\'s Stone")).Click();
    driver.FindElement(By.CssSelector(".back-button")).Click();
    driver.Close();
  }
  [Test]
  public void paginationTest() {
    driver.Navigate().GoToUrl("https://shemulhossain.github.io/EAD_CA3/");
    driver.Manage().Window.Size = new System.Drawing.Size(968, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-input"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".search-input")).Click();
    driver.FindElement(By.CssSelector(".search-input")).SendKeys("Harry Potter");
    driver.FindElement(By.CssSelector(".search-button")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".pagination-button:nth-child(1)")).Click();
    driver.Close();
  }
  [Test]
  public void searchTest() {
    driver.Navigate().GoToUrl("https://shemulhossain.github.io/EAD_CA3/");
    driver.Manage().Window.Size = new System.Drawing.Size(968, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-input"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".search-input")).Click();
    driver.FindElement(By.CssSelector(".search-input")).SendKeys("Harry Potter");
    driver.FindElement(By.CssSelector(".search-button")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.Close();
  }
}
